# Generated by Django 4.2 on 2023-06-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofestival',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
