# Generated by Django 4.2 on 2023-06-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_videofestival_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofestival',
            name='order',
        ),
    ]
