# Generated by Django 4.0 on 2023-04-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='task',
        ),
    ]
