# Generated by Django 4.0 on 2023-04-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_user_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='uname',
        ),
    ]
