# Generated by Django 4.0 on 2023-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APItest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('age', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('mobileno', models.CharField(max_length=15)),
            ],
        ),
    ]
