# Generated by Django 4.2 on 2023-05-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitest',
            name='password',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
