# Generated by Django 4.0 on 2023-04-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vdieo',
            new_name='video',
        ),
    ]
