# Generated by Django 4.0 on 2023-04-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_video_caption_video_agegroup_video_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APItest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('age', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('mobileno', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='agegroup',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='DEFAULT VALUE', upload_to='video/%y'),
        ),
    ]
