# Generated by Django 4.0 on 2023-04-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_apitest_alter_video_agegroup_alter_video_topic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APItest',
        ),
    ]
